# Generated by Django 4.2.7 on 2023-11-13 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='metric',
            index=models.Index(fields=['timestamp'], name='metrics_met_timesta_98f825_idx'),
        ),
    ]
