# Generated by Django 4.2.7 on 2023-11-13 03:12

from datetime import timedelta
from django.utils import timezone
from django.db import migrations


def create_initial_metrics(apps, schema_editor):
    Metric = apps.get_model('metrics', 'Metric')
    Metric.objects.create(timestamp=timezone.now(), name='Metric1', value=10.0)
    Metric.objects.create(timestamp=timezone.now()+timedelta(minutes=-5), name='Metric1', value=15.0)
    Metric.objects.create(timestamp=timezone.now()+timedelta(days=-1), name='Metric1', value=20.0)

    Metric.objects.create(timestamp=timezone.now(), name='Metric2', value=12.0)
    Metric.objects.create(timestamp=timezone.now()+timedelta(minutes=-35), name='Metric2', value=23.0)
    Metric.objects.create(timestamp=timezone.now()+timedelta(days=-3), name='Metric2', value=34.0)

    Metric.objects.create(timestamp=timezone.now(), name='Metric3', value=0.4)
    Metric.objects.create(timestamp=timezone.now()+timedelta(hours=-2), name='Metric3', value=1.25)
    Metric.objects.create(timestamp=timezone.now()+timedelta(hours=-8), name='Metric3', value=0.8)


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_metric_metrics_met_timesta_98f825_idx'),
    ]

    operations = [
        migrations.RunPython(create_initial_metrics),
    ]
